modLoader = "javafml"
loaderVersion = "[46,)"
issueTrackerURL = "https://github.com/erha134/Mrs-Craft-Town/issues/"
license = "GPLv3-or-later"

[[mods]]
modId = "mrscrafttown"
version = "${version}"
displayName = "Mr's Craft Town Mod"
#updateJSONURL=""
displayURL="https://modrinth.com/mod/mrscrafttown/"
authors = "erha134 (Mr_limr233/Mrlimr267)"
credits = "Mr_zmh5"
description = '''
A Minecraft Mod.
'''
logoFile = "icon.png"

[[dependencies.mrscrafttown]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mrscrafttown]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20, 1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mrscrafttown]]
modId = "architectury"
mandatory = true
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mrscrafttown]]
modId = "midnightlib"
mandatory = true
versionRange = "[0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.easiertravelcraft]]
modId = "kiwi"
mandatory = true
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"
